### ISSUE TITLE
Getting weird results. What am I doing wrong?

### ISSUE THREAD

**Issue by nitinmukesh** [jdh-algo/JoyVASA#3]
Thank you for sharing your work.

Is this how it's supposed to work? The videos on project page are awesome

python inference.py -r assets/face1.png -a assets/audio.wav --animation_mode human --cfg_scale 2.0

cfg_scale 0.0

https://github.com/user-attachments/assets/d35db0f0-eaa9-43f3-8a15-5e1384335576

cfg_scale 1.0

https://github.com/user-attachments/assets/ac74d92c-3077-4eeb-96c9-cbd55c61eb9e

cfg_scale 2.0

https://github.com/user-attachments/assets/bb50974a-72d6-4431-b8f7-c9e14a63a5ff

cfg_scale 3.0

https://github.com/user-attachments/assets/0bf63419-af80-4ca5-93b5-1438cc1017d7

**Comment by xuyangcao** [comment]
> Thank you for sharing your work.
> 
> Is this how it's supposed to work? The videos on project page are awesome
> 
> python inference.py -r assets/face1.png -a assets/audio.wav --animation_mode human --cfg_scale 2.0
> 

Thank you for your interest in our work and for trying out our approach. Your basic operations are correct, but you might improve the results by adjusting the hyperparameters related to Liveportrait in the `src/config/argument_config.py`. Despite this, we've also encountered similar suboptimal results in practice. One reason for this is that the final outcomes of our method are influenced by the first stage. Specifically, the Liveportrait model used in the first stage shows suboptimal performance when dealing with large pose variations, which affects the quality of the generated outputs. Additionally, Liveportrait includes a retargeting module designed for cross-identity reference images, which is not suitable for pure audio-driven portrait animation. As a result, this limitation also impacts the quality of the generated results. In future work, we plan to explore more robust face representation techniques, such as [EMOPortrait](https://github.com/neeek2303/EMOPortraits), to address these issues. These limitations are discussed in our paper for your reference.

**Comment by nitinmukesh** [comment]
Appreciate your explanation. Please could you share how you achieved the results on Demo page. Settings, assets, etc.

I will try if the similar results can be achieved.

**Comment by xuyangcao** [comment]
> Appreciate your explanation. Please could you share how you achieved the results on Demo page. Settings, assets, etc.
> 
> I will try if the similar results can be achieved.

Sure, we will update the assets soon.
